name: Format check

on:
  push:
    branches:
      - 'main'
    tags: '*'
  pull_request:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: julia-actions/setup-julia@5c9647d97b78a5debe5164e9eec09d653d29bd71 # v2.6.1
        with:
          version: '1.10'

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Install JuliaFormatter and format
        run: |
          julia --color=yes -e 'using Pkg; Pkg.add(PackageSpec(name="JuliaFormatter", version="1.0.62"))'
          julia --color=yes -e 'using JuliaFormatter; format(".", verbose=true)'
      - name: Format Check
        run: |
          julia -e '
          out = Cmd(`git diff --name-only`) |> read |> String
          if out == ""
              exit(0)
          else
              @error "Some files have not been formatted !!!"
              write(stdout, out)
              exit(1)
          end'
