---
name: "TagBot"

on:
  issue_comment:
    types:
      - "created"
  workflow_dispatch:

jobs:
  TagBot:
    if: |
      github.event_name == 'workflow_dispatch' ||
      (
        github.actor == 'ChrisRackauckas' &&
        startsWith(github.event.comment.body, 'Triggering TagBot')
      )
    runs-on: "self-hosted"
    steps:
      - uses: "JuliaRegistries/TagBot@62dd7cd21dcde087eca10e70c3fc3f8cefbe44a2" # v1
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          ssh: "${{ secrets.JULIASIM_REGISTRY_SSH_KEY }}"
          registry: "JuliaComputing/JuliaSimRegistry"
          registry_ssh: "${{ secrets.JULIASIM_REGISTRY_SSH_KEY }}"
